Feature/Login-components
gabrielgomesml/training_project_client pull request #1
Opened 2022-02-01 16:25 UTC by gabrielgomesml

## What I did

- Create base of the project;
- Create Login components and page;
- Create Login hook;
- Create Private Routes;

## How to test

- First of all make sure you are running the server in your machine. You can check the steps here: https://github.com/gabrielgomesml/training_project_server/pull/1
- Open the project and use the command `nvm use`
- Run a `yarn` or `yarn install`
- After that run the command `yarn start` to start the project
- Try to access `localhost:8080/test` route. You should be redirect to login page;
- Log into an existing account and check the localstorage of the page. You should see the user info and a token;
- Last, click and the logout button and your credentials should be removed from localstorage.

2022-02-01 19:30 UTC, JonasMazza requested changes
Let's talk about all this tomorrow?

2022-02-01 19:30 UTC, JonasMazza commented on src/index.tsx
> +  <Router>
the Router could be inside the App

2022-02-01 19:30 UTC, JonasMazza commented on src/hooks/index.tsx
> +  <AuthProvider>{children}</AuthProvider>
this could be inside the App, also this is not a hook but is in a /hooks/ folder

2022-02-01 19:30 UTC, JonasMazza commented on src/hooks/auth.tsx
> +const AuthContext = createContext<AuthContextProps>({} as AuthContextProps);
bad assertion, see line 58

2022-02-01 19:30 UTC, JonasMazza commented on src/components/Button/style.ts
> +  background: ${(props: ButtonProps) => props.backgroundColor || 'white'};
No need to type the `props` here, it should be correctly inferred by TS. Always let TS infer the types when possible.

2022-02-01 19:30 UTC, JonasMazza commented on src/components/Button/style.ts
> +export interface ButtonProps {
If these props will be passed down to a styled component you might be leaking them to the dom node. One solution is to use transient props. Check this: https://medium.com/@probablyup/introducing-transient-props-f35fd5203e0c

2022-02-01 19:30 UTC, JonasMazza commented on src/components/Input/index.tsx
> +}: InputProps) => {
what if I want to use any other default <input> prop, like id, className, style, for... ?

2022-02-01 19:30 UTC, JonasMazza commented on src/components/Button/index.tsx
> +  width?: number;
it looks like this could've been solved with a simple inline styling, do you intend to extend the behavior of this Button component later?

2022-02-04 16:48 UTC, gabrielgomesml commented on src/hooks/auth.tsx
> +  const signOut = useCallback(() => {
i changed from localstorage to cookies for now, by i'm still searching a better way to protect this. For now, i'm thinking this way can be satisfying to keep moving our project progress.

2022-02-09 17:19 UTC, JonasMazza approved these changes

2022-02-09 17:20 UTC, merged